server:
  port: 8001

spring:
  rabbitmq:
    host: 127.0.0.1
    username: dxj
    password: 123456
    virtual-host: /leyou

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/skadmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
