server:
  port: 8002

spring:
  data:
    elasticsearch:
      cluster-name: singwa_imooc
      cluster-nodes: 127.0.0.1:9300

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/skadmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    org.springframework:
      debug
